repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.8.4"
    hooks:
        - id: ruff
          args: [ "--fix", "--exit-non-zero-on-fix" ]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args:
          - "--line-length=120"
          - "--target-version=py310"
          - "--target-version=py311"
        types: [ python ]

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.21
    hooks:
      - id: uv-lock